name: learn-github-actions
run-name: ${{github.actor}} is learning Github Action
on: ["push"]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g bats
      - run: bats -v
  check-pnpm-version:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: pwd # 展示当前目录
      - run: npm install pnpm -g
      - run: pnpm -v
